name: Daily Fetch

# Trigger the workflow on a schedule and manually (one-time trigger)
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        run: npm run fetch

      - name: Check if files changed
        run: |
          git diff --exit-code || echo "Files have changed"

      - name: Commit changes if files were updated
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update nvc-bundle.js and nvc-bundle.json" || echo "No changes to commit"

      - name: Push changes to repository
        run: |
          git push origin main  # Adjust if your branch is different
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}